server:
  port: 9201
spring:
  application:
    name: novice-example-service2
  cloud:
    novice:
      discovery:
        server-addr: 127.0.0.1:9527
logging:
  level:
    root: info
    com.novice: debug
